# Generated by Django 4.1.7 on 2023-04-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0002_reviewus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewus',
            name='message',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
